#!/bin/sh
set -e
TAR_FILE="/tmp/release.tar.gz"
DOWNLOAD_URL="https://github.com/goreleaser/releaser/releases/download"
test -z "$TMPDIR" && TMPDIR="$(mktemp -d)"

last_version() {
  curl -s https://raw.githubusercontent.com/goreleaser/homebrew-tap/master/Formula/goreleaser.rb |
    grep url |
    cut -f8 -d'/'
}

download() {
  version="$(last_version)"
  test -z "$version" && {
    echo "Unable to get goreleaser version." >&2
    exit 1
  }
  rm -f "$TAR_FILE"
  curl -s -L -o "$TAR_FILE" \
    "$DOWNLOAD_URL/$version/release_$(uname -s)_$(uname -m).tar.gz"
}

download
tar -xf "$TAR_FILE" -C "$TMPDIR"
"${TMPDIR}/release"
